---
title: "Lab_8"
author: "Anna Schiller"
date: "3/8/2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


load packaged
```{r, echo =FALSE}
library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)

```

### Column Graph of texas Oil Spills

```{r}

oils_spills<- read_csv("oil_spills.csv") # can use this read_csv instead of read.csv because we have downloaded tidyverse, this reads it as a table dF?

df<- oils_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year`<2017) %>%  # if there's a space in your column
  group_by(`Accident Year`) %>% 
  summarise( Loss = sum(`Net Loss (Barrels)`)) #creates new column that summarizes

colnames(df) <- c("Year", "Loss")

ggplot(df, aes(x=Year, y= Loss)) +
  geom_col()

```
### Spatial info, leaflet plit of spill locations
```{r}

df_loc<- oils_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` == 2016) %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`)

colnames(df_loc) <- c("lat", "long", "net_loss")

oil_sf<- st_as_sf(df_loc, coords= c("long", "lat"), crs =4326)  #convert to simple features spatial data, can treat as dataframe but will retain spatial features

class(oil_sf)

leaflet(oil_sf) %>% 
  addTiles() %>% 
  addMarkers()


```

## Point pattern analysis TMAP with the texas state shapefile

```{r}

states<-st_read( dsn = ".", layer = "states" )

tex_border<- states %>% 
  filter(STATE_NAME == "Texas") %>% 
  st_transform(4326)

plot(tex_border)

tm_shape(tex_border) +
           tm_polygons()+
  tm_shape(oil_sf)+
  tm_dots(size= 0.3)

```

## Convert data to spatial points patterns (combination of point data and the bounding window)

```{r}

spill_sp <- as(oil_sf, "Spatial") #create spatial datafram
spill_ppp<- as(spill_sp, "ppp") # changes to point pattern class of data

tx_sp<- as(tex_border, "Spatial")
tx_owin <- as(tx_sp,"owin")

all_ppp<- ppp(spill_ppp$x, spill_ppp$y, window = tx_owin)
  
  
```

